### ISSUE TITLE
Task completion error

### ISSUE THREAD

**Issue by Akira30903** [NAHIAN-19/Todo-List-Django#2]
You cant add the completed task in completed

**Comment by NAHIAN-19** [comment]
> You cant add the completed task in completed

![image](https://github.com/NAHIAN-19/Todo-List-Django/assets/106859103/0aac9950-40c2-4ae3-ae78-3b0cf68eedab)
Did you meant this status change?

**Comment by NAHIAN-19** [comment]
> You cant add the completed task in completed

![image](https://github.com/NAHIAN-19/Todo-List-Django/assets/106859103/c829b44a-2dcc-449a-a52c-16f8d8c2c8cc)
Did you meant this status change? If not then can you provide a screenshot of the error you are facing?

**Comment by NAHIAN-19** [comment]
> You cant add the completed task in completed

Solved!
