### ISSUE TITLE
Please remove __pycache__ and migrations folders from your github repo

### ISSUE THREAD

**Issue by AKRASH-Nadeem** [NAHIAN-19/Todo-List-Django#3]
Please remove `__pycache__` and `migrations` folders from your github repo

also remove zip files please

**Comment by NAHIAN-19** [comment]
> Please remove `__pycache__` and `migrations` folders from your github repo
> 
> also remove zip files please


Hi Nadeem, I've removed the __pycache__ and migrations folders, excluding the __init__.py files, and also deleted the zip files from the repository. If there's anything else you need, just let me know!

Thanks for pointing this out.

**Comment by AKRASH-Nadeem** [comment]
Thanks it is better now
